# Generated by Django 2.2 on 2021-07-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appforbooksandauthors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='coding'),
            preserve_default=False,
        ),
    ]
